import Header from './header'
import Footer from './footer'
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;500;600;700&display=swap"
          rel="stylesheet" />
      </Head>
      <main>{children}</main>
      <Footer />
    </>
  );
}

export default Layout;
