import Head from "next/head";
import Header from "../components/Header";

const Services = () => {
  return (
    <div>
      <Head>
        <title>TechDots</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section className="banner">
          <Header />
        </section>
      </main>
    </div>
  );
};

export default Services;
